# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  my_job:
    runs-on: ubuntu-18.04
    container:
      image: node:10.16-jessie
    steps:
    - uses: actions/checkout@v2
